name: Build and publish client user android

runs:
  using: composite
  steps:
    - name: Generate environment
      shell: bash
      run: |
        ./gradlew :client:apps:user:core:generateEnvironment -Penvironment="production(android[KEYSTORE_PASSWORD=Password123,KEY_ALIAS=key0,KEY_PASSWORD=Password123,KEYSTORE_PATH=dev/debug-keystore.jks,IS_DEBUG=false,PROTOCOL=https,HOST=url]:native[IS_DEBUG=false,PROTOCOL=https,HOST=url]:wasm[IS_DEBUG=false])"

    - name: Select environment
      shell: bash
      run: |
        ./gradlew :client:apps:user:core:selectEnvironment -PnewSelectedEnvironment=production

    - name: Build apk
      shell: bash
      run: |
        ./gradlew :client:apps:user:core:assembleRelease

    - name: Publish apk
      uses: softprops/action-gh-release@v3
      with:
        files: |
          ./client/apps/user/core/build/outputs/apk/release/core-release.apk