name: Build client user ios

runs:
  using: composite
  steps:
    - name: Build app
      shell: bash
      run: |
        xcodebuild clean archive \
          -project client/apps/user/iosApp/iosApp.xcodeproj \
          -scheme "iosApp" \
          -configuration Release \
          -sdk iphoneos \
          -archivePath client/apps/user/iosApp/build/iosApp.xcarchive \
          CODE_SIGN_IDENTITY="" \
          CODE_SIGNING_REQUIRED=NO \
          CODE_SIGNING_ALLOWED=NO \
          DEVELOPMENT_TEAM=""

    - name: Zip ipa
      shell: bash
      run: |
        mkdir client/apps/user/iosApp/build/Payload
        cp -r client/apps/user/iosApp/build/iosApp.xcarchive/Products/Applications/oneclick.app client/apps/user/iosApp/build/Payload
        (cd client/apps/user/iosApp/build && zip -qr oneclick.ipa Payload)