name: Build client user ios

runs:
  using: composite
  steps:
    - name: Build app
      shell: bash
      working-directory: client/apps/user/iosApp
      run: |
        xcodebuild clean archive \
          -project iosApp.xcodeproj \
          -scheme "iosApp" \
          -configuration Release \
          -sdk iphoneos \
          -archivePath build/iosApp.xcarchive \
          CODE_SIGN_IDENTITY="" \
          CODE_SIGNING_REQUIRED=NO \
          CODE_SIGNING_ALLOWED=NO \
          DEVELOPMENT_TEAM=""

    - name: Zip ipa
      shell: bash
      working-directory: client/apps/user/iosApp
      run: |
        mkdir build/Payload
        cp -r build/iosApp.xcarchive/Products/Applications/oneclick.app build/Payload
        (cd build && zip -qr oneclick.ipa Payload)