name: Deploy

on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.ref }}
  cancel-in-progress: true

permissions:
  contents: write
  packages: write

defaults:
  run:
    shell: bash

jobs:
  deploy:
    runs-on: macos-latest
    timeout-minutes: 60

    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Setup
        uses: ./.github/actions/setup-action

      - name: Build and publish client user app android
        uses: ./.github/actions/build-and-publish-client-user-android

      - name: Build and publish client user app ios
        uses: ./.github/actions/build-and-publish-client-user-ios

      - name: Build and publish home app
        uses: ./.github/actions/build-and-publish-client-home
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and publish server app
        uses: ./.github/actions/build-and-publish-server-app
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Publish apk and ipa
        uses: softprops/action-gh-release@v3
        with:
          files: |
            ./client/apps/user/core/build/outputs/apk/release/core-release.apk
            ./client/apps/iosApp/build/oneclick.ipa