name: Deploy

on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.ref }}
  cancel-in-progress: true

permissions:
  contents: write
  packages: write

defaults:
  run:
    shell: bash

jobs:
  deploy:
    runs-on: macos-latest
    timeout-minutes: 60

    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Setup
        uses: ./.github/actions/setup-action

      - name: Build and upload client user app
        uses: ./.github/actions/build-and-publish-client-user

      - name: Build and publish home app
        uses: ./.github/actions/build-and-publish-client-home

      - name: Build and publish server app
        uses: ./.github/actions/build-and-publish-server-app